version: '3.8'
services:
  react-app:
    image: library-local-fe
    ports:
      - "8080:80"
    environment:
      - REACT_APP_API_URL="http://host.docker.internal:8081"
    networks:
      - mynetwork
  api:
    image: libarary-local-api
    ports:
      - "8081:8081"
    networks:
      - mynetwork
    healthcheck:
      test: [ "CMD", "curl", "--location", "http://localhost:8081" ]
      interval: 10s
      timeout: 5s
      retries: 3
networks:
  mynetwork:
    name: mynetwork
