apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: 'jtabaku/generalimages:v2.0'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: db-password
              value: "1234"
            - name: db-host
              value: "db-service"
            - name: db-name
              value: "lib2"
            - name: db-port
              value: "5433"
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30100
  selector:
    app: api

